{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "0be69fc6-354c-4f86-9991-73cb64785fcd",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd \n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from sklearn.impute import SimpleImputer\n",
    "from sklearn.ensemble import RandomForestClassifier\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import accuracy_score,classification_report\n",
    "from sklearn.preprocessing import StandardScaler,MinMaxScaler,RobustScaler,LabelEncoder,OneHotEncoder\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "411d437c-1116-4009-82cd-c35148e4f18f",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv(\"adult_with_headers.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "d942d28b-4e9a-497f-90bf-5c708912e7c3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(32561, 15)"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "60674331-c40e-40f3-9b5a-dabd851b1593",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "age               0\n",
       "workclass         0\n",
       "fnlwgt            0\n",
       "education         0\n",
       "education_num     0\n",
       "marital_status    0\n",
       "occupation        0\n",
       "relationship      0\n",
       "race              0\n",
       "sex               0\n",
       "capital_gain      0\n",
       "capital_loss      0\n",
       "hours_per_week    0\n",
       "native_country    0\n",
       "income            0\n",
       "dtype: int64"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.isnull().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "a2762e32-8e53-4f5b-a4a5-b2b5a700c990",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "24"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.duplicated().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "b567a852-1bf3-4edf-bc74-b257dd293209",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.drop_duplicates(inplace=True,ignore_index=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "1b006d3d-7d5f-441b-88f9-2d172abf9049",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "age                  73\n",
       "workclass             9\n",
       "fnlwgt            21648\n",
       "education            16\n",
       "education_num        16\n",
       "marital_status        7\n",
       "occupation           15\n",
       "relationship          6\n",
       "race                  5\n",
       "sex                   2\n",
       "capital_gain        119\n",
       "capital_loss         92\n",
       "hours_per_week       94\n",
       "native_country       42\n",
       "income                2\n",
       "dtype: int64"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.nunique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "7c8f4e44-46ff-40c5-a5be-61bd68a4f216",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>age</th>\n",
       "      <th>workclass</th>\n",
       "      <th>fnlwgt</th>\n",
       "      <th>education</th>\n",
       "      <th>education_num</th>\n",
       "      <th>marital_status</th>\n",
       "      <th>occupation</th>\n",
       "      <th>relationship</th>\n",
       "      <th>race</th>\n",
       "      <th>sex</th>\n",
       "      <th>capital_gain</th>\n",
       "      <th>capital_loss</th>\n",
       "      <th>hours_per_week</th>\n",
       "      <th>native_country</th>\n",
       "      <th>income</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>39</td>\n",
       "      <td>State-gov</td>\n",
       "      <td>77516</td>\n",
       "      <td>Bachelors</td>\n",
       "      <td>13</td>\n",
       "      <td>Never-married</td>\n",
       "      <td>Adm-clerical</td>\n",
       "      <td>Not-in-family</td>\n",
       "      <td>White</td>\n",
       "      <td>Male</td>\n",
       "      <td>2174</td>\n",
       "      <td>0</td>\n",
       "      <td>40</td>\n",
       "      <td>United-States</td>\n",
       "      <td>&lt;=50K</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>50</td>\n",
       "      <td>Self-emp-not-inc</td>\n",
       "      <td>83311</td>\n",
       "      <td>Bachelors</td>\n",
       "      <td>13</td>\n",
       "      <td>Married-civ-spouse</td>\n",
       "      <td>Exec-managerial</td>\n",
       "      <td>Husband</td>\n",
       "      <td>White</td>\n",
       "      <td>Male</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>13</td>\n",
       "      <td>United-States</td>\n",
       "      <td>&lt;=50K</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>38</td>\n",
       "      <td>Private</td>\n",
       "      <td>215646</td>\n",
       "      <td>HS-grad</td>\n",
       "      <td>9</td>\n",
       "      <td>Divorced</td>\n",
       "      <td>Handlers-cleaners</td>\n",
       "      <td>Not-in-family</td>\n",
       "      <td>White</td>\n",
       "      <td>Male</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>40</td>\n",
       "      <td>United-States</td>\n",
       "      <td>&lt;=50K</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>53</td>\n",
       "      <td>Private</td>\n",
       "      <td>234721</td>\n",
       "      <td>11th</td>\n",
       "      <td>7</td>\n",
       "      <td>Married-civ-spouse</td>\n",
       "      <td>Handlers-cleaners</td>\n",
       "      <td>Husband</td>\n",
       "      <td>Black</td>\n",
       "      <td>Male</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>40</td>\n",
       "      <td>United-States</td>\n",
       "      <td>&lt;=50K</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>28</td>\n",
       "      <td>Private</td>\n",
       "      <td>338409</td>\n",
       "      <td>Bachelors</td>\n",
       "      <td>13</td>\n",
       "      <td>Married-civ-spouse</td>\n",
       "      <td>Prof-specialty</td>\n",
       "      <td>Wife</td>\n",
       "      <td>Black</td>\n",
       "      <td>Female</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>40</td>\n",
       "      <td>Cuba</td>\n",
       "      <td>&lt;=50K</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   age          workclass  fnlwgt   education  education_num  \\\n",
       "0   39          State-gov   77516   Bachelors             13   \n",
       "1   50   Self-emp-not-inc   83311   Bachelors             13   \n",
       "2   38            Private  215646     HS-grad              9   \n",
       "3   53            Private  234721        11th              7   \n",
       "4   28            Private  338409   Bachelors             13   \n",
       "\n",
       "        marital_status          occupation    relationship    race      sex  \\\n",
       "0        Never-married        Adm-clerical   Not-in-family   White     Male   \n",
       "1   Married-civ-spouse     Exec-managerial         Husband   White     Male   \n",
       "2             Divorced   Handlers-cleaners   Not-in-family   White     Male   \n",
       "3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   \n",
       "4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   \n",
       "\n",
       "   capital_gain  capital_loss  hours_per_week  native_country  income  \n",
       "0          2174             0              40   United-States   <=50K  \n",
       "1             0             0              13   United-States   <=50K  \n",
       "2             0             0              40   United-States   <=50K  \n",
       "3             0             0              40   United-States   <=50K  \n",
       "4             0             0              40            Cuba   <=50K  "
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "4eb5f8e5-6195-4628-8023-a5d2b8c1b0e6",
   "metadata": {},
   "outputs": [],
   "source": [
    "df['capital_diff'] = df['capital_gain'] - df['capital_loss']\n",
    "df['age_group'] = pd.cut(df['age'], \n",
    "                         bins=[0, 25, 45, 65, 100], \n",
    "                         labels=['Young', 'Adult', 'Senior', 'Old'])\n",
    "df['work_hour_level'] = pd.cut(df['hours_per_week'], \n",
    "                               bins=[0, 20, 40, 60, 100], \n",
    "                               labels=['Low', 'Medium', 'High', 'Very High'])\n",
    "df['is_married'] = df['marital_status'].apply(lambda x: 1 if 'Married' in x else 0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "7a93b35d-eab8-4b75-9fce-b10903b75c48",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.drop(df[['capital_gain','capital_loss','hours_per_week','marital_status','age']],axis=1,inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "c80f0da5-7e88-46bf-8915-afb9dc8ebca3",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>workclass</th>\n",
       "      <th>fnlwgt</th>\n",
       "      <th>education</th>\n",
       "      <th>education_num</th>\n",
       "      <th>occupation</th>\n",
       "      <th>relationship</th>\n",
       "      <th>race</th>\n",
       "      <th>sex</th>\n",
       "      <th>native_country</th>\n",
       "      <th>income</th>\n",
       "      <th>capital_diff</th>\n",
       "      <th>age_group</th>\n",
       "      <th>work_hour_level</th>\n",
       "      <th>is_married</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>State-gov</td>\n",
       "      <td>77516</td>\n",
       "      <td>Bachelors</td>\n",
       "      <td>13</td>\n",
       "      <td>Adm-clerical</td>\n",
       "      <td>Not-in-family</td>\n",
       "      <td>White</td>\n",
       "      <td>Male</td>\n",
       "      <td>United-States</td>\n",
       "      <td>&lt;=50K</td>\n",
       "      <td>2174</td>\n",
       "      <td>Adult</td>\n",
       "      <td>Medium</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Self-emp-not-inc</td>\n",
       "      <td>83311</td>\n",
       "      <td>Bachelors</td>\n",
       "      <td>13</td>\n",
       "      <td>Exec-managerial</td>\n",
       "      <td>Husband</td>\n",
       "      <td>White</td>\n",
       "      <td>Male</td>\n",
       "      <td>United-States</td>\n",
       "      <td>&lt;=50K</td>\n",
       "      <td>0</td>\n",
       "      <td>Senior</td>\n",
       "      <td>Low</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Private</td>\n",
       "      <td>215646</td>\n",
       "      <td>HS-grad</td>\n",
       "      <td>9</td>\n",
       "      <td>Handlers-cleaners</td>\n",
       "      <td>Not-in-family</td>\n",
       "      <td>White</td>\n",
       "      <td>Male</td>\n",
       "      <td>United-States</td>\n",
       "      <td>&lt;=50K</td>\n",
       "      <td>0</td>\n",
       "      <td>Adult</td>\n",
       "      <td>Medium</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Private</td>\n",
       "      <td>234721</td>\n",
       "      <td>11th</td>\n",
       "      <td>7</td>\n",
       "      <td>Handlers-cleaners</td>\n",
       "      <td>Husband</td>\n",
       "      <td>Black</td>\n",
       "      <td>Male</td>\n",
       "      <td>United-States</td>\n",
       "      <td>&lt;=50K</td>\n",
       "      <td>0</td>\n",
       "      <td>Senior</td>\n",
       "      <td>Medium</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Private</td>\n",
       "      <td>338409</td>\n",
       "      <td>Bachelors</td>\n",
       "      <td>13</td>\n",
       "      <td>Prof-specialty</td>\n",
       "      <td>Wife</td>\n",
       "      <td>Black</td>\n",
       "      <td>Female</td>\n",
       "      <td>Cuba</td>\n",
       "      <td>&lt;=50K</td>\n",
       "      <td>0</td>\n",
       "      <td>Adult</td>\n",
       "      <td>Medium</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "           workclass  fnlwgt   education  education_num          occupation  \\\n",
       "0          State-gov   77516   Bachelors             13        Adm-clerical   \n",
       "1   Self-emp-not-inc   83311   Bachelors             13     Exec-managerial   \n",
       "2            Private  215646     HS-grad              9   Handlers-cleaners   \n",
       "3            Private  234721        11th              7   Handlers-cleaners   \n",
       "4            Private  338409   Bachelors             13      Prof-specialty   \n",
       "\n",
       "     relationship    race      sex  native_country  income  capital_diff  \\\n",
       "0   Not-in-family   White     Male   United-States   <=50K          2174   \n",
       "1         Husband   White     Male   United-States   <=50K             0   \n",
       "2   Not-in-family   White     Male   United-States   <=50K             0   \n",
       "3         Husband   Black     Male   United-States   <=50K             0   \n",
       "4            Wife   Black   Female            Cuba   <=50K             0   \n",
       "\n",
       "  age_group work_hour_level  is_married  \n",
       "0     Adult          Medium           0  \n",
       "1    Senior             Low           1  \n",
       "2     Adult          Medium           0  \n",
       "3    Senior          Medium           1  \n",
       "4     Adult          Medium           1  "
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "0815c25c-b204-416d-9f0b-f9d0fcbffcf7",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "workclass\n",
       "Private             22673\n",
       "Self-emp-not-inc     2540\n",
       "Local-gov            2093\n",
       "?                    1836\n",
       "State-gov            1298\n",
       "Self-emp-inc         1116\n",
       "Federal-gov           960\n",
       "Without-pay            14\n",
       "Never-worked            7\n",
       "Name: count, dtype: int64"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.workclass.value_counts()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "bd39250f-3ea0-4b3c-8a51-75c6767dc5bc",
   "metadata": {},
   "outputs": [],
   "source": [
    "df['workclass']=df['workclass'].str.strip()\n",
    "df['workclass'].replace('?',np.nan,inplace=True)\n",
    "df.dropna(subset=['workclass'],inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "56fa732b-15d1-49bc-b1c7-bcc40147e512",
   "metadata": {},
   "outputs": [],
   "source": [
    "df['occupation']=df['occupation'].str.strip()\n",
    "df['occupation'].replace('?',np.nan,inplace=True)\n",
    "df.dropna(subset=['occupation'],inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "18162a79-7aa6-449b-9d1e-dc4fd46e2330",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "relationship\n",
       "Husband           12698\n",
       "Not-in-family      7852\n",
       "Own-child          4521\n",
       "Unmarried          3270\n",
       "Wife               1435\n",
       "Other-relative      918\n",
       "Name: count, dtype: int64"
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.relationship.value_counts()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "c4dad2f5-e96b-4713-9531-07f30f10e248",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "69"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.duplicated().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "f147f986-7848-405e-84a6-12e768b14056",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.drop_duplicates(inplace=True,ignore_index=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "248e2e03-6c35-4813-a591-414b516f0ae7",
   "metadata": {},
   "outputs": [],
   "source": [
    "label = LabelEncoder()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "d46b4e84-641d-4431-8e1c-80d9bc27a616",
   "metadata": {},
   "outputs": [],
   "source": [
    "df.columns = df.columns.str.strip()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "1196c2df-48c7-4c99-b2db-25ac215ee937",
   "metadata": {},
   "outputs": [],
   "source": [
    "(df['age_group'])=label.fit_transform(df['age_group'])\n",
    "(df['race'])=label.fit_transform(df['race'])\n",
    "(df['work_hour_level'])=label.fit_transform(df['work_hour_level'])\n",
    "(df['sex'])=label.fit_transform(df['sex'])\n",
    "(df['income'])=label.fit_transform(df['income'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "f76922eb-d6c8-42e5-861f-10692e8bdef2",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>workclass</th>\n",
       "      <th>fnlwgt</th>\n",
       "      <th>education</th>\n",
       "      <th>education_num</th>\n",
       "      <th>occupation</th>\n",
       "      <th>relationship</th>\n",
       "      <th>race</th>\n",
       "      <th>sex</th>\n",
       "      <th>native_country</th>\n",
       "      <th>income</th>\n",
       "      <th>capital_diff</th>\n",
       "      <th>age_group</th>\n",
       "      <th>work_hour_level</th>\n",
       "      <th>is_married</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>State-gov</td>\n",
       "      <td>77516</td>\n",
       "      <td>Bachelors</td>\n",
       "      <td>13</td>\n",
       "      <td>Adm-clerical</td>\n",
       "      <td>Not-in-family</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>United-States</td>\n",
       "      <td>0</td>\n",
       "      <td>2174</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Self-emp-not-inc</td>\n",
       "      <td>83311</td>\n",
       "      <td>Bachelors</td>\n",
       "      <td>13</td>\n",
       "      <td>Exec-managerial</td>\n",
       "      <td>Husband</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>United-States</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Private</td>\n",
       "      <td>215646</td>\n",
       "      <td>HS-grad</td>\n",
       "      <td>9</td>\n",
       "      <td>Handlers-cleaners</td>\n",
       "      <td>Not-in-family</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>United-States</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Private</td>\n",
       "      <td>234721</td>\n",
       "      <td>11th</td>\n",
       "      <td>7</td>\n",
       "      <td>Handlers-cleaners</td>\n",
       "      <td>Husband</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>United-States</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Private</td>\n",
       "      <td>338409</td>\n",
       "      <td>Bachelors</td>\n",
       "      <td>13</td>\n",
       "      <td>Prof-specialty</td>\n",
       "      <td>Wife</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>Cuba</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "          workclass  fnlwgt   education  education_num         occupation  \\\n",
       "0         State-gov   77516   Bachelors             13       Adm-clerical   \n",
       "1  Self-emp-not-inc   83311   Bachelors             13    Exec-managerial   \n",
       "2           Private  215646     HS-grad              9  Handlers-cleaners   \n",
       "3           Private  234721        11th              7  Handlers-cleaners   \n",
       "4           Private  338409   Bachelors             13     Prof-specialty   \n",
       "\n",
       "     relationship  race  sex  native_country  income  capital_diff  age_group  \\\n",
       "0   Not-in-family     4    1   United-States       0          2174          0   \n",
       "1         Husband     4    1   United-States       0             0          2   \n",
       "2   Not-in-family     4    1   United-States       0             0          0   \n",
       "3         Husband     2    1   United-States       0             0          2   \n",
       "4            Wife     2    0            Cuba       0             0          0   \n",
       "\n",
       "   work_hour_level  is_married  \n",
       "0                2           0  \n",
       "1                1           1  \n",
       "2                2           0  \n",
       "3                2           1  \n",
       "4                2           1  "
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "7c8af3df-2f00-4ace-893d-bf95994b5d7c",
   "metadata": {},
   "outputs": [],
   "source": [
    "df['workclass'].drop_duplicates(inplace=True,ignore_index=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "04bc27f1-4f96-4a49-b584-ad586c1eb969",
   "metadata": {},
   "outputs": [],
   "source": [
    "df=pd.concat([df.drop('workclass',axis=1), pd.get_dummies(df['workclass'],drop_first=True,sparse=True,dtype=int)],axis=1)\n",
    "df=pd.concat([df.drop('education',axis=1), pd.get_dummies(df['education'],drop_first=True,sparse=True,dtype=int)],axis=1)\n",
    "df=pd.concat([df.drop('education_num',axis=1), pd.get_dummies(df['education_num'],drop_first=True,sparse=True,dtype=int)],axis=1)\n",
    "df=pd.concat([df.drop('relationship',axis=1), pd.get_dummies(df['relationship'],drop_first=True,sparse=True,dtype=int)],axis=1)\n",
    "df=pd.concat([df.drop('native_country',axis=1), pd.get_dummies(df['native_country'],drop_first=True,sparse=True,dtype=int)],axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "8eb32595-f124-43fd-9211-283daacb07d2",
   "metadata": {},
   "outputs": [],
   "source": [
    "df=pd.concat([df.drop('occupation',axis=1), pd.get_dummies(df['occupation'],drop_first=True,sparse=True,dtype=int)],axis=1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "e7f1f688-9eea-4632-a27e-2d9105feda0d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>fnlwgt</th>\n",
       "      <th>race</th>\n",
       "      <th>sex</th>\n",
       "      <th>income</th>\n",
       "      <th>capital_diff</th>\n",
       "      <th>age_group</th>\n",
       "      <th>work_hour_level</th>\n",
       "      <th>is_married</th>\n",
       "      <th>Local-gov</th>\n",
       "      <th>Private</th>\n",
       "      <th>...</th>\n",
       "      <th>Farming-fishing</th>\n",
       "      <th>Handlers-cleaners</th>\n",
       "      <th>Machine-op-inspct</th>\n",
       "      <th>Other-service</th>\n",
       "      <th>Priv-house-serv</th>\n",
       "      <th>Prof-specialty</th>\n",
       "      <th>Protective-serv</th>\n",
       "      <th>Sales</th>\n",
       "      <th>Tech-support</th>\n",
       "      <th>Transport-moving</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>77516</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>2174</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>83311</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>215646</td>\n",
       "      <td>4</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>234721</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>338409</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 103 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   fnlwgt  race  sex  income  capital_diff  age_group  work_hour_level  \\\n",
       "0   77516     4    1       0          2174          0                2   \n",
       "1   83311     4    1       0             0          2                1   \n",
       "2  215646     4    1       0             0          0                2   \n",
       "3  234721     2    1       0             0          2                2   \n",
       "4  338409     2    0       0             0          0                2   \n",
       "\n",
       "   is_married  Local-gov  Private  ...  Farming-fishing  Handlers-cleaners  \\\n",
       "0           0          0        0  ...                0                  0   \n",
       "1           1          0        0  ...                0                  0   \n",
       "2           0          0        1  ...                0                  1   \n",
       "3           1          0        1  ...                0                  1   \n",
       "4           1          0        1  ...                0                  0   \n",
       "\n",
       "   Machine-op-inspct  Other-service  Priv-house-serv  Prof-specialty  \\\n",
       "0                  0              0                0               0   \n",
       "1                  0              0                0               0   \n",
       "2                  0              0                0               0   \n",
       "3                  0              0                0               0   \n",
       "4                  0              0                0               1   \n",
       "\n",
       "   Protective-serv  Sales  Tech-support  Transport-moving  \n",
       "0                0      0             0                 0  \n",
       "1                0      0             0                 0  \n",
       "2                0      0             0                 0  \n",
       "3                0      0             0                 0  \n",
       "4                0      0             0                 0  \n",
       "\n",
       "[5 rows x 103 columns]"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "d04f51d1-4c04-40a2-ae59-d14b87571c23",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(30625, 103)"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "2a6c66ff-21e2-48e9-b964-12b5466dd191",
   "metadata": {},
   "outputs": [],
   "source": [
    "minax = MinMaxScaler()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "e0049c16-5717-4691-87a2-203d0a414198",
   "metadata": {},
   "outputs": [],
   "source": [
    "df[['fnlwgt','capital_diff','race','work_hour_level','age_group']]=minax.fit_transform(df[['fnlwgt','age_group','capital_diff','race','work_hour_level']]).round(3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "5c1ab501-85a9-4e9a-9cde-8edeb294feaa",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>fnlwgt</th>\n",
       "      <th>race</th>\n",
       "      <th>sex</th>\n",
       "      <th>income</th>\n",
       "      <th>capital_diff</th>\n",
       "      <th>age_group</th>\n",
       "      <th>work_hour_level</th>\n",
       "      <th>is_married</th>\n",
       "      <th>Local-gov</th>\n",
       "      <th>Private</th>\n",
       "      <th>...</th>\n",
       "      <th>Farming-fishing</th>\n",
       "      <th>Handlers-cleaners</th>\n",
       "      <th>Machine-op-inspct</th>\n",
       "      <th>Other-service</th>\n",
       "      <th>Priv-house-serv</th>\n",
       "      <th>Prof-specialty</th>\n",
       "      <th>Protective-serv</th>\n",
       "      <th>Sales</th>\n",
       "      <th>Tech-support</th>\n",
       "      <th>Transport-moving</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>0.043</td>\n",
       "      <td>0.063</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0.000</td>\n",
       "      <td>0.667</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>0.047</td>\n",
       "      <td>0.042</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0.667</td>\n",
       "      <td>0.333</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>0.137</td>\n",
       "      <td>0.042</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0.000</td>\n",
       "      <td>0.667</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>0.150</td>\n",
       "      <td>0.042</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0.667</td>\n",
       "      <td>0.667</td>\n",
       "      <td>0.5</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>0.221</td>\n",
       "      <td>0.042</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0.000</td>\n",
       "      <td>0.667</td>\n",
       "      <td>0.5</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>...</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 103 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   fnlwgt   race  sex  income  capital_diff  age_group  work_hour_level  \\\n",
       "0   0.043  0.063    1       0         0.000      0.667              1.0   \n",
       "1   0.047  0.042    1       0         0.667      0.333              1.0   \n",
       "2   0.137  0.042    1       0         0.000      0.667              1.0   \n",
       "3   0.150  0.042    1       0         0.667      0.667              0.5   \n",
       "4   0.221  0.042    0       0         0.000      0.667              0.5   \n",
       "\n",
       "   is_married  Local-gov  Private  ...  Farming-fishing  Handlers-cleaners  \\\n",
       "0           0          0        0  ...                0                  0   \n",
       "1           1          0        0  ...                0                  0   \n",
       "2           0          0        1  ...                0                  1   \n",
       "3           1          0        1  ...                0                  1   \n",
       "4           1          0        1  ...                0                  0   \n",
       "\n",
       "   Machine-op-inspct  Other-service  Priv-house-serv  Prof-specialty  \\\n",
       "0                  0              0                0               0   \n",
       "1                  0              0                0               0   \n",
       "2                  0              0                0               0   \n",
       "3                  0              0                0               0   \n",
       "4                  0              0                0               1   \n",
       "\n",
       "   Protective-serv  Sales  Tech-support  Transport-moving  \n",
       "0                0      0             0                 0  \n",
       "1                0      0             0                 0  \n",
       "2                0      0             0                 0  \n",
       "3                0      0             0                 0  \n",
       "4                0      0             0                 0  \n",
       "\n",
       "[5 rows x 103 columns]"
      ]
     },
     "execution_count": 29,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "6d82c532-eda8-482a-b841-82999aba3351",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>fnlwgt</th>\n",
       "      <th>race</th>\n",
       "      <th>sex</th>\n",
       "      <th>income</th>\n",
       "      <th>capital_diff</th>\n",
       "      <th>age_group</th>\n",
       "      <th>work_hour_level</th>\n",
       "      <th>is_married</th>\n",
       "      <th>Local-gov</th>\n",
       "      <th>Private</th>\n",
       "      <th>...</th>\n",
       "      <th>Farming-fishing</th>\n",
       "      <th>Handlers-cleaners</th>\n",
       "      <th>Machine-op-inspct</th>\n",
       "      <th>Other-service</th>\n",
       "      <th>Priv-house-serv</th>\n",
       "      <th>Prof-specialty</th>\n",
       "      <th>Protective-serv</th>\n",
       "      <th>Sales</th>\n",
       "      <th>Tech-support</th>\n",
       "      <th>Transport-moving</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>fnlwgt</th>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.000304</td>\n",
       "      <td>0.026632</td>\n",
       "      <td>-0.009496</td>\n",
       "      <td>0.007010</td>\n",
       "      <td>0.021620</td>\n",
       "      <td>-0.023738</td>\n",
       "      <td>-0.026895</td>\n",
       "      <td>-0.003208</td>\n",
       "      <td>0.046756</td>\n",
       "      <td>...</td>\n",
       "      <td>-0.034265</td>\n",
       "      <td>0.029489</td>\n",
       "      <td>0.012702</td>\n",
       "      <td>-0.004437</td>\n",
       "      <td>0.007472</td>\n",
       "      <td>-0.017305</td>\n",
       "      <td>0.016945</td>\n",
       "      <td>0.003248</td>\n",
       "      <td>0.004017</td>\n",
       "      <td>0.001048</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>race</th>\n",
       "      <td>0.000304</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.045065</td>\n",
       "      <td>0.212937</td>\n",
       "      <td>-0.008088</td>\n",
       "      <td>-0.041095</td>\n",
       "      <td>0.010342</td>\n",
       "      <td>0.079445</td>\n",
       "      <td>-0.009007</td>\n",
       "      <td>-0.046305</td>\n",
       "      <td>...</td>\n",
       "      <td>-0.011945</td>\n",
       "      <td>-0.023136</td>\n",
       "      <td>-0.026367</td>\n",
       "      <td>-0.039793</td>\n",
       "      <td>-0.006990</td>\n",
       "      <td>0.082587</td>\n",
       "      <td>-0.007621</td>\n",
       "      <td>0.009937</td>\n",
       "      <td>-0.010415</td>\n",
       "      <td>-0.019025</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>sex</th>\n",
       "      <td>0.026632</td>\n",
       "      <td>0.045065</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.216524</td>\n",
       "      <td>-0.071673</td>\n",
       "      <td>-0.121888</td>\n",
       "      <td>0.085807</td>\n",
       "      <td>0.424729</td>\n",
       "      <td>-0.043987</td>\n",
       "      <td>-0.065367</td>\n",
       "      <td>...</td>\n",
       "      <td>0.100665</td>\n",
       "      <td>0.093696</td>\n",
       "      <td>0.027360</td>\n",
       "      <td>-0.165280</td>\n",
       "      <td>-0.092461</td>\n",
       "      <td>-0.036113</td>\n",
       "      <td>0.064788</td>\n",
       "      <td>-0.017966</td>\n",
       "      <td>-0.019124</td>\n",
       "      <td>0.133748</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>income</th>\n",
       "      <td>-0.009496</td>\n",
       "      <td>0.212937</td>\n",
       "      <td>0.216524</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>-0.117085</td>\n",
       "      <td>-0.170761</td>\n",
       "      <td>0.070769</td>\n",
       "      <td>0.435341</td>\n",
       "      <td>0.028369</td>\n",
       "      <td>-0.117588</td>\n",
       "      <td>...</td>\n",
       "      <td>-0.056388</td>\n",
       "      <td>-0.093075</td>\n",
       "      <td>-0.076106</td>\n",
       "      <td>-0.166205</td>\n",
       "      <td>-0.038948</td>\n",
       "      <td>0.182344</td>\n",
       "      <td>0.025723</td>\n",
       "      <td>0.017292</td>\n",
       "      <td>0.022912</td>\n",
       "      <td>-0.026612</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>capital_diff</th>\n",
       "      <td>0.007010</td>\n",
       "      <td>-0.008088</td>\n",
       "      <td>-0.071673</td>\n",
       "      <td>-0.117085</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.057232</td>\n",
       "      <td>0.030128</td>\n",
       "      <td>-0.184104</td>\n",
       "      <td>-0.029603</td>\n",
       "      <td>0.049414</td>\n",
       "      <td>...</td>\n",
       "      <td>0.006816</td>\n",
       "      <td>0.059117</td>\n",
       "      <td>-0.009924</td>\n",
       "      <td>0.101276</td>\n",
       "      <td>0.026411</td>\n",
       "      <td>-0.067714</td>\n",
       "      <td>-0.022268</td>\n",
       "      <td>0.056487</td>\n",
       "      <td>-0.018161</td>\n",
       "      <td>-0.020585</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Prof-specialty</th>\n",
       "      <td>-0.017305</td>\n",
       "      <td>0.082587</td>\n",
       "      <td>-0.036113</td>\n",
       "      <td>0.182344</td>\n",
       "      <td>-0.067714</td>\n",
       "      <td>-0.058962</td>\n",
       "      <td>0.019171</td>\n",
       "      <td>0.035718</td>\n",
       "      <td>0.160115</td>\n",
       "      <td>-0.161903</td>\n",
       "      <td>...</td>\n",
       "      <td>-0.072210</td>\n",
       "      <td>-0.085287</td>\n",
       "      <td>-0.104263</td>\n",
       "      <td>-0.136734</td>\n",
       "      <td>-0.027423</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>-0.058102</td>\n",
       "      <td>-0.145093</td>\n",
       "      <td>-0.069725</td>\n",
       "      <td>-0.092618</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Protective-serv</th>\n",
       "      <td>0.016945</td>\n",
       "      <td>-0.007621</td>\n",
       "      <td>0.064788</td>\n",
       "      <td>0.025723</td>\n",
       "      <td>-0.022268</td>\n",
       "      <td>0.015521</td>\n",
       "      <td>-0.019340</td>\n",
       "      <td>0.034986</td>\n",
       "      <td>0.233290</td>\n",
       "      <td>-0.149103</td>\n",
       "      <td>...</td>\n",
       "      <td>-0.026908</td>\n",
       "      <td>-0.031781</td>\n",
       "      <td>-0.038852</td>\n",
       "      <td>-0.050952</td>\n",
       "      <td>-0.010219</td>\n",
       "      <td>-0.058102</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>-0.054066</td>\n",
       "      <td>-0.025982</td>\n",
       "      <td>-0.034513</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Sales</th>\n",
       "      <td>0.003248</td>\n",
       "      <td>0.009937</td>\n",
       "      <td>-0.017966</td>\n",
       "      <td>0.017292</td>\n",
       "      <td>0.056487</td>\n",
       "      <td>-0.077757</td>\n",
       "      <td>0.029084</td>\n",
       "      <td>-0.010857</td>\n",
       "      <td>-0.096722</td>\n",
       "      <td>0.056365</td>\n",
       "      <td>...</td>\n",
       "      <td>-0.067195</td>\n",
       "      <td>-0.079364</td>\n",
       "      <td>-0.097022</td>\n",
       "      <td>-0.127238</td>\n",
       "      <td>-0.025519</td>\n",
       "      <td>-0.145093</td>\n",
       "      <td>-0.054066</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>-0.064882</td>\n",
       "      <td>-0.086186</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Tech-support</th>\n",
       "      <td>0.004017</td>\n",
       "      <td>-0.010415</td>\n",
       "      <td>-0.019124</td>\n",
       "      <td>0.022912</td>\n",
       "      <td>-0.018161</td>\n",
       "      <td>0.024996</td>\n",
       "      <td>0.003471</td>\n",
       "      <td>-0.013367</td>\n",
       "      <td>-0.019108</td>\n",
       "      <td>0.021866</td>\n",
       "      <td>...</td>\n",
       "      <td>-0.032291</td>\n",
       "      <td>-0.038139</td>\n",
       "      <td>-0.046624</td>\n",
       "      <td>-0.061145</td>\n",
       "      <td>-0.012263</td>\n",
       "      <td>-0.069725</td>\n",
       "      <td>-0.025982</td>\n",
       "      <td>-0.064882</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>-0.041417</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>Transport-moving</th>\n",
       "      <td>0.001048</td>\n",
       "      <td>-0.019025</td>\n",
       "      <td>0.133748</td>\n",
       "      <td>-0.026612</td>\n",
       "      <td>-0.020585</td>\n",
       "      <td>-0.018563</td>\n",
       "      <td>-0.001979</td>\n",
       "      <td>0.072463</td>\n",
       "      <td>0.003409</td>\n",
       "      <td>0.029088</td>\n",
       "      <td>...</td>\n",
       "      <td>-0.042893</td>\n",
       "      <td>-0.050661</td>\n",
       "      <td>-0.061933</td>\n",
       "      <td>-0.081221</td>\n",
       "      <td>-0.016290</td>\n",
       "      <td>-0.092618</td>\n",
       "      <td>-0.034513</td>\n",
       "      <td>-0.086186</td>\n",
       "      <td>-0.041417</td>\n",
       "      <td>1.000000</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>103 rows × 103 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                    fnlwgt      race       sex    income  capital_diff  \\\n",
       "fnlwgt            1.000000  0.000304  0.026632 -0.009496      0.007010   \n",
       "race              0.000304  1.000000  0.045065  0.212937     -0.008088   \n",
       "sex               0.026632  0.045065  1.000000  0.216524     -0.071673   \n",
       "income           -0.009496  0.212937  0.216524  1.000000     -0.117085   \n",
       "capital_diff      0.007010 -0.008088 -0.071673 -0.117085      1.000000   \n",
       "...                    ...       ...       ...       ...           ...   \n",
       "Prof-specialty   -0.017305  0.082587 -0.036113  0.182344     -0.067714   \n",
       "Protective-serv   0.016945 -0.007621  0.064788  0.025723     -0.022268   \n",
       "Sales             0.003248  0.009937 -0.017966  0.017292      0.056487   \n",
       "Tech-support      0.004017 -0.010415 -0.019124  0.022912     -0.018161   \n",
       "Transport-moving  0.001048 -0.019025  0.133748 -0.026612     -0.020585   \n",
       "\n",
       "                  age_group  work_hour_level  is_married  Local-gov   Private  \\\n",
       "fnlwgt             0.021620        -0.023738   -0.026895  -0.003208  0.046756   \n",
       "race              -0.041095         0.010342    0.079445  -0.009007 -0.046305   \n",
       "sex               -0.121888         0.085807    0.424729  -0.043987 -0.065367   \n",
       "income            -0.170761         0.070769    0.435341   0.028369 -0.117588   \n",
       "capital_diff       0.057232         0.030128   -0.184104  -0.029603  0.049414   \n",
       "...                     ...              ...         ...        ...       ...   \n",
       "Prof-specialty    -0.058962         0.019171    0.035718   0.160115 -0.161903   \n",
       "Protective-serv    0.015521        -0.019340    0.034986   0.233290 -0.149103   \n",
       "Sales             -0.077757         0.029084   -0.010857  -0.096722  0.056365   \n",
       "Tech-support       0.024996         0.003471   -0.013367  -0.019108  0.021866   \n",
       "Transport-moving  -0.018563        -0.001979    0.072463   0.003409  0.029088   \n",
       "\n",
       "                  ...  Farming-fishing  Handlers-cleaners  Machine-op-inspct  \\\n",
       "fnlwgt            ...        -0.034265           0.029489           0.012702   \n",
       "race              ...        -0.011945          -0.023136          -0.026367   \n",
       "sex               ...         0.100665           0.093696           0.027360   \n",
       "income            ...        -0.056388          -0.093075          -0.076106   \n",
       "capital_diff      ...         0.006816           0.059117          -0.009924   \n",
       "...               ...              ...                ...                ...   \n",
       "Prof-specialty    ...        -0.072210          -0.085287          -0.104263   \n",
       "Protective-serv   ...        -0.026908          -0.031781          -0.038852   \n",
       "Sales             ...        -0.067195          -0.079364          -0.097022   \n",
       "Tech-support      ...        -0.032291          -0.038139          -0.046624   \n",
       "Transport-moving  ...        -0.042893          -0.050661          -0.061933   \n",
       "\n",
       "                  Other-service  Priv-house-serv  Prof-specialty  \\\n",
       "fnlwgt                -0.004437         0.007472       -0.017305   \n",
       "race                  -0.039793        -0.006990        0.082587   \n",
       "sex                   -0.165280        -0.092461       -0.036113   \n",
       "income                -0.166205        -0.038948        0.182344   \n",
       "capital_diff           0.101276         0.026411       -0.067714   \n",
       "...                         ...              ...             ...   \n",
       "Prof-specialty        -0.136734        -0.027423        1.000000   \n",
       "Protective-serv       -0.050952        -0.010219       -0.058102   \n",
       "Sales                 -0.127238        -0.025519       -0.145093   \n",
       "Tech-support          -0.061145        -0.012263       -0.069725   \n",
       "Transport-moving      -0.081221        -0.016290       -0.092618   \n",
       "\n",
       "                  Protective-serv     Sales  Tech-support  Transport-moving  \n",
       "fnlwgt                   0.016945  0.003248      0.004017          0.001048  \n",
       "race                    -0.007621  0.009937     -0.010415         -0.019025  \n",
       "sex                      0.064788 -0.017966     -0.019124          0.133748  \n",
       "income                   0.025723  0.017292      0.022912         -0.026612  \n",
       "capital_diff            -0.022268  0.056487     -0.018161         -0.020585  \n",
       "...                           ...       ...           ...               ...  \n",
       "Prof-specialty          -0.058102 -0.145093     -0.069725         -0.092618  \n",
       "Protective-serv          1.000000 -0.054066     -0.025982         -0.034513  \n",
       "Sales                   -0.054066  1.000000     -0.064882         -0.086186  \n",
       "Tech-support            -0.025982 -0.064882      1.000000         -0.041417  \n",
       "Transport-moving        -0.034513 -0.086186     -0.041417          1.000000  \n",
       "\n",
       "[103 rows x 103 columns]"
      ]
     },
     "execution_count": 30,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.corr()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f3287a81-9354-4749-ac19-9b171cb1b2be",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
